version: '3.4'

services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  catalog.api:
    image: catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/BookStore.Api/dockerfile
    ports:
      - "8000:80"
    depends_on:
      - sql.data
